// Code generated by mfd-generator v0.6.1; DO NOT EDIT.

//nolint:all
//lint:file-ignore U1000 ignore unused code, it's generated
package db

import (
	"time"
)

var Columns = struct {
	User struct {
		ID, CreatedAt, Login, Password, AuthKey, LastActivityAt, StatusID string
	}
	AppUser struct {
		ID, Login, Password, Name, Surname string
	}
	TaskFile struct {
		TaskID, FileID string

		Task, File string
	}
	Task struct {
		ID, Title, Description, CreatedAt, IsDeadline, UserID, DeadLine, StatusID string

		User string
	}
	TaskStatus struct {
		StatusID, Title, Alias string
	}
	VfsFile struct {
		ID, FolderID, Title, Path, Params, IsFavorite, MimeType, FileSize, FileExists, CreatedAt, StatusID string

		Folder string
	}
	VfsFolder struct {
		ID, ParentFolderID, Title, IsFavorite, CreatedAt, StatusID string

		ParentFolder string
	}
}{
	User: struct {
		ID, CreatedAt, Login, Password, AuthKey, LastActivityAt, StatusID string
	}{
		ID:             "userId",
		CreatedAt:      "createdAt",
		Login:          "login",
		Password:       "password",
		AuthKey:        "authKey",
		LastActivityAt: "lastActivityAt",
		StatusID:       "statusId",
	},
	AppUser: struct {
		ID, Login, Password, Name, Surname string
	}{
		ID:       "id",
		Login:    "login",
		Password: "password",
		Name:     "name",
		Surname:  "surname",
	},
	TaskFile: struct {
		TaskID, FileID string

		Task, File string
	}{
		TaskID: "task_id",
		FileID: "file_id",

		Task: "Task",
		File: "File",
	},
	Task: struct {
		ID, Title, Description, CreatedAt, IsDeadline, UserID, DeadLine, StatusID string

		User string
	}{
		ID:          "id",
		Title:       "title",
		Description: "description",
		CreatedAt:   "created_at",
		IsDeadline:  "is_deadline",
		UserID:      "user_id",
		DeadLine:    "dead_line",
		StatusID:    "statusId",

		User: "User",
	},
	TaskStatus: struct {
		StatusID, Title, Alias string
	}{
		StatusID: "statusId",
		Title:    "title",
		Alias:    "alias",
	},
	VfsFile: struct {
		ID, FolderID, Title, Path, Params, IsFavorite, MimeType, FileSize, FileExists, CreatedAt, StatusID string

		Folder string
	}{
		ID:         "fileId",
		FolderID:   "folderId",
		Title:      "title",
		Path:       "path",
		Params:     "params",
		IsFavorite: "isFavorite",
		MimeType:   "mimeType",
		FileSize:   "fileSize",
		FileExists: "fileExists",
		CreatedAt:  "createdAt",
		StatusID:   "statusId",

		Folder: "Folder",
	},
	VfsFolder: struct {
		ID, ParentFolderID, Title, IsFavorite, CreatedAt, StatusID string

		ParentFolder string
	}{
		ID:             "folderId",
		ParentFolderID: "parentFolderId",
		Title:          "title",
		IsFavorite:     "isFavorite",
		CreatedAt:      "createdAt",
		StatusID:       "statusId",

		ParentFolder: "ParentFolder",
	},
}

var Tables = struct {
	User struct {
		Name, Alias string
	}
	AppUser struct {
		Name, Alias string
	}
	TaskFile struct {
		Name, Alias string
	}
	Task struct {
		Name, Alias string
	}
	TaskStatus struct {
		Name, Alias string
	}
	VfsFile struct {
		Name, Alias string
	}
	VfsFolder struct {
		Name, Alias string
	}
}{
	User: struct {
		Name, Alias string
	}{
		Name:  "users",
		Alias: "t",
	},
	AppUser: struct {
		Name, Alias string
	}{
		Name:  "app_users",
		Alias: "t",
	},
	TaskFile: struct {
		Name, Alias string
	}{
		Name:  "task_files",
		Alias: "t",
	},
	Task: struct {
		Name, Alias string
	}{
		Name:  "tasks",
		Alias: "t",
	},
	TaskStatus: struct {
		Name, Alias string
	}{
		Name:  "task_statuses",
		Alias: "t",
	},
	VfsFile: struct {
		Name, Alias string
	}{
		Name:  "vfsFiles",
		Alias: "t",
	},
	VfsFolder: struct {
		Name, Alias string
	}{
		Name:  "vfsFolders",
		Alias: "t",
	},
}

type User struct {
	tableName struct{} `pg:"users,alias:t,discard_unknown_columns"`

	ID             int        `pg:"userId,pk"`
	CreatedAt      time.Time  `pg:"createdAt,use_zero"`
	Login          string     `pg:"login,use_zero"`
	Password       string     `pg:"password,use_zero"`
	AuthKey        string     `pg:"authKey,use_zero"`
	LastActivityAt *time.Time `pg:"lastActivityAt"`
	StatusID       int        `pg:"statusId,use_zero"`
}

type AppUser struct {
	tableName struct{} `pg:"app_users,alias:t,discard_unknown_columns"`

	ID       int64   `pg:"id,pk"`
	Login    string  `pg:"login,use_zero"`
	Password string  `pg:"password,use_zero"`
	Name     *string `pg:"name"`
	Surname  *string `pg:"surname"`
}

type TaskFile struct {
	tableName struct{} `pg:"task_files,alias:t,discard_unknown_columns"`

	TaskID *int64 `pg:"task_id"`
	FileID *int64 `pg:"file_id"`

	Task *Task    `pg:"fk:task_id,rel:has-one"`
	File *VfsFile `pg:"fk:file_id,rel:has-one"`
}

type Task struct {
	tableName struct{} `pg:"tasks,alias:t,discard_unknown_columns"`

	ID          int64      `pg:"id,pk"`
	Title       string     `pg:"title,use_zero"`
	Description *string    `pg:"description"`
	CreatedAt   time.Time  `pg:"created_at,use_zero"`
	IsDeadline  *bool      `pg:"is_deadline"`
	UserID      *int64     `pg:"user_id"`
	DeadLine    *time.Time `pg:"dead_line"`
	StatusID    int        `pg:"statusId,use_zero"`

	User *AppUser `pg:"fk:user_id,rel:has-one"`
}

type TaskStatus struct {
	tableName struct{} `pg:"task_statuses,alias:t,discard_unknown_columns"`

	StatusID int    `pg:"statusId,use_zero"`
	Title    string `pg:"title,use_zero"`
	Alias    string `pg:"alias,use_zero"`
}

type VfsFile struct {
	tableName struct{} `pg:"vfsFiles,alias:t,discard_unknown_columns"`

	ID         int       `pg:"fileId,pk"`
	FolderID   int       `pg:"folderId,use_zero"`
	Title      string    `pg:"title,use_zero"`
	Path       string    `pg:"path,use_zero"`
	Params     *string   `pg:"params"`
	IsFavorite *bool     `pg:"isFavorite"`
	MimeType   string    `pg:"mimeType,use_zero"`
	FileSize   *int      `pg:"fileSize"`
	FileExists bool      `pg:"fileExists,use_zero"`
	CreatedAt  time.Time `pg:"createdAt,use_zero"`
	StatusID   int       `pg:"statusId,use_zero"`

	Folder *VfsFolder `pg:"fk:folderId,rel:has-one"`
}

type VfsFolder struct {
	tableName struct{} `pg:"vfsFolders,alias:t,discard_unknown_columns"`

	ID             int       `pg:"folderId,pk"`
	ParentFolderID *int      `pg:"parentFolderId"`
	Title          string    `pg:"title,use_zero"`
	IsFavorite     *bool     `pg:"isFavorite"`
	CreatedAt      time.Time `pg:"createdAt,use_zero"`
	StatusID       int       `pg:"statusId,use_zero"`

	ParentFolder *VfsFolder `pg:"fk:parentFolderId,rel:has-one"`
}
