// Code generated by mfd-generator v0.6.1; DO NOT EDIT.

//nolint:all
//lint:file-ignore U1000 ignore unused code, it's generated
package db

import (
	"unicode/utf8"
)

const (
	ErrEmptyValue = "empty"
	ErrMaxLength  = "len"
	ErrWrongValue = "value"
)

func (u User) Validate() (errors map[string]string, valid bool) {
	errors = map[string]string{}

	if utf8.RuneCountInString(u.Login) > 64 {
		errors[Columns.User.Login] = ErrMaxLength
	}

	if utf8.RuneCountInString(u.Password) > 64 {
		errors[Columns.User.Password] = ErrMaxLength
	}

	if utf8.RuneCountInString(u.AuthKey) > 32 {
		errors[Columns.User.AuthKey] = ErrMaxLength
	}

	return errors, len(errors) == 0
}

func (au AppUser) Validate() (errors map[string]string, valid bool) {
	errors = map[string]string{}

	if utf8.RuneCountInString(au.Login) > 255 {
		errors[Columns.AppUser.Login] = ErrMaxLength
	}

	if utf8.RuneCountInString(au.Password) > 255 {
		errors[Columns.AppUser.Password] = ErrMaxLength
	}

	if au.Surname != nil && utf8.RuneCountInString(*au.Surname) > 255 {
		errors[Columns.AppUser.Surname] = ErrMaxLength
	}

	return errors, len(errors) == 0
}

func (t Task) Validate() (errors map[string]string, valid bool) {
	errors = map[string]string{}

	if utf8.RuneCountInString(t.Title) > 255 {
		errors[Columns.Task.Title] = ErrMaxLength
	}

	if t.Description != nil && utf8.RuneCountInString(*t.Description) > 255 {
		errors[Columns.Task.Description] = ErrMaxLength
	}

	return errors, len(errors) == 0
}

func (ts TaskStatus) Validate() (errors map[string]string, valid bool) {
	errors = map[string]string{}

	if utf8.RuneCountInString(ts.Title) > 255 {
		errors[Columns.TaskStatus.Title] = ErrMaxLength
	}

	if utf8.RuneCountInString(ts.Alias) > 64 {
		errors[Columns.TaskStatus.Alias] = ErrMaxLength
	}

	return errors, len(errors) == 0
}

func (vf VfsFile) Validate() (errors map[string]string, valid bool) {
	errors = map[string]string{}

	if utf8.RuneCountInString(vf.Title) > 255 {
		errors[Columns.VfsFile.Title] = ErrMaxLength
	}

	if utf8.RuneCountInString(vf.Path) > 255 {
		errors[Columns.VfsFile.Path] = ErrMaxLength
	}

	if utf8.RuneCountInString(vf.MimeType) > 255 {
		errors[Columns.VfsFile.MimeType] = ErrMaxLength
	}

	return errors, len(errors) == 0
}

func (vf VfsFolder) Validate() (errors map[string]string, valid bool) {
	errors = map[string]string{}

	if utf8.RuneCountInString(vf.Title) > 255 {
		errors[Columns.VfsFolder.Title] = ErrMaxLength
	}

	return errors, len(errors) == 0
}
