// Code generated by colgen v0.1.3; DO NOT EDIT.
package task

import (
	"apisrv/pkg/db"
)

type ServiceStatusList []ServiceStatus

func (ll ServiceStatusList) IDs() []int {
	r := make([]int, len(ll))
	for i := range ll {
		r[i] = ll[i].ID
	}
	return r
}

func (ll ServiceStatusList) Index() map[int]ServiceStatus {
	r := make(map[int]ServiceStatus, len(ll))
	for i := range ll {
		r[ll[i].ID] = ll[i]
	}
	return r
}

func NewServiceStatusList(in []db.TaskStatus) ServiceStatusList { return Map(in, NewServiceStatus) }

type ServiceTaskList []ServiceTask

func (ll ServiceTaskList) IDs() []int64 {
	r := make([]int64, len(ll))
	for i := range ll {
		r[i] = ll[i].ID
	}
	return r
}

func (ll ServiceTaskList) Index() map[int64]ServiceTask {
	r := make(map[int64]ServiceTask, len(ll))
	for i := range ll {
		r[ll[i].ID] = ll[i]
	}
	return r
}

func NewServiceTaskList(in []db.Task) ServiceTaskList { return Map(in, NewServiceTask) }
