[App]
Table = "public.pgMigrations"
StatementTimeout = "5s"
Filemask = "\\d{4}-\\d{2}-\\d{2}-\\S+.sql"

[Database]
Addr = "localhost:5432"
User = "mikhail"
Password = "postgres"
Database = "task_planner"
PoolSize = 1
ApplicationName = "pgmigrator"


