// Code generated by colgen v0.1.3; DO NOT EDIT.
package rpc

import tasks "apisrv/pkg/goldapi/task"

type StatusResponseList []StatusResponse

func (ll StatusResponseList) IDs() []int {
	r := make([]int, len(ll))
	for i := range ll {
		r[i] = ll[i].ID
	}
	return r
}

func (ll StatusResponseList) Index() map[int]StatusResponse {
	r := make(map[int]StatusResponse, len(ll))
	for i := range ll {
		r[ll[i].ID] = ll[i]
	}
	return r
}

func NewStatusResponseList(in []tasks.ServiceStatus) StatusResponseList {
	return Map(in, NewStatusResponse)
}

type TaskResponseList []TaskResponse

func (ll TaskResponseList) IDs() []int64 {
	r := make([]int64, len(ll))
	for i := range ll {
		r[i] = ll[i].ID
	}
	return r
}

func (ll TaskResponseList) Index() map[int64]TaskResponse {
	r := make(map[int64]TaskResponse, len(ll))
	for i := range ll {
		r[ll[i].ID] = ll[i]
	}
	return r
}

func NewTaskResponseList(in []tasks.ServiceTask) TaskResponseList { return Map(in, NewTaskResponse) }
