// Code generated by zenrpc v2.3.1; DO NOT EDIT.

package rpc

import (
	"context"
	"encoding/json"

	"github.com/vmkteam/zenrpc/v2"
	"github.com/vmkteam/zenrpc/v2/smd"
)

var RPC = struct {
	TaskService struct{ CreateTask, GetTaskByPeriod, UpdateTitle, UpdateDescription, UpdateDeadLine, DeleteTask, UpdateStatus, GetStatuses string }
}{
	TaskService: struct{ CreateTask, GetTaskByPeriod, UpdateTitle, UpdateDescription, UpdateDeadLine, DeleteTask, UpdateStatus, GetStatuses string }{
		CreateTask:        "createtask",
		GetTaskByPeriod:   "gettaskbyperiod",
		UpdateTitle:       "updatetitle",
		UpdateDescription: "updatedescription",
		UpdateDeadLine:    "updatedeadline",
		DeleteTask:        "deletetask",
		UpdateStatus:      "updatestatus",
		GetStatuses:       "getstatuses",
	},
}

func (TaskService) SMD() smd.ServiceInfo {
	return smd.ServiceInfo{
		Methods: map[string]smd.Service{
			"CreateTask": {
				Parameters: []smd.JSONSchema{
					{
						Name:     "req",
						Type:     smd.Object,
						TypeName: "CreateTaskRequest",
						Properties: smd.PropertyList{
							{
								Name: "userId",
								Type: smd.Integer,
							},
							{
								Name: "Title",
								Type: smd.String,
							},
							{
								Name:     "description",
								Optional: true,
								Type:     smd.String,
							},
							{
								Name:     "deadline",
								Optional: true,
								Type:     smd.String,
							},
						},
					},
				},
				Returns: smd.JSONSchema{
					Type:     smd.Object,
					TypeName: "CreateTaskResponse",
					Properties: smd.PropertyList{
						{
							Name: "taskId",
							Type: smd.Integer,
						},
					},
				},
			},
			"GetTaskByPeriod": {
				Parameters: []smd.JSONSchema{
					{
						Name:     "req",
						Type:     smd.Object,
						TypeName: "GetTaskByPeriodRequest",
						Properties: smd.PropertyList{
							{
								Name: "userId",
								Type: smd.Integer,
							},
							{
								Name: "periodStart",
								Type: smd.String,
							},
							{
								Name: "periodEnd",
								Type: smd.String,
							},
						},
					},
				},
				Returns: smd.JSONSchema{
					Type:     smd.Object,
					TypeName: "GetTaskByPeriodResponse",
					Properties: smd.PropertyList{
						{
							Name: "tasks",
							Type: smd.Array,
							Items: map[string]string{
								"$ref": "#/definitions/TaskResponse",
							},
						},
					},
					Definitions: map[string]smd.Definition{
						"TaskResponse": {
							Type: "object",
							Properties: smd.PropertyList{
								{
									Name: "id",
									Type: smd.Integer,
								},
								{
									Name: "title",
									Type: smd.String,
								},
								{
									Name:     "description",
									Optional: true,
									Type:     smd.String,
								},
								{
									Name:     "isDeadline",
									Optional: true,
									Type:     smd.Boolean,
								},
								{
									Name:     "deadline",
									Optional: true,
									Type:     smd.String,
								},
								{
									Name: "statusId",
									Type: smd.Integer,
								},
								{
									Name: "Name",
									Type: smd.String,
								},
								{
									Name:     "deadLine",
									Optional: true,
									Type:     smd.String,
								},
								{
									Name: "createdAt",
									Type: smd.String,
								},
							},
						},
					},
				},
			},
			"UpdateTitle": {
				Parameters: []smd.JSONSchema{
					{
						Name:     "req",
						Type:     smd.Object,
						TypeName: "UpdateTitleRequest",
						Properties: smd.PropertyList{
							{
								Name: "taskId",
								Type: smd.Integer,
							},
							{
								Name: "title",
								Type: smd.String,
							},
						},
					},
				},
			},
			"UpdateDescription": {
				Parameters: []smd.JSONSchema{
					{
						Name:     "req",
						Type:     smd.Object,
						TypeName: "UpdateDescriptionRequest",
						Properties: smd.PropertyList{
							{
								Name: "taskId",
								Type: smd.Integer,
							},
							{
								Name: "description",
								Type: smd.String,
							},
						},
					},
				},
			},
			"UpdateDeadLine": {
				Parameters: []smd.JSONSchema{
					{
						Name:     "req",
						Type:     smd.Object,
						TypeName: "UpdateDeadLineRequest",
						Properties: smd.PropertyList{
							{
								Name: "taskId",
								Type: smd.Integer,
							},
							{
								Name: "deadline",
								Type: smd.String,
							},
						},
					},
				},
			},
			"DeleteTask": {
				Parameters: []smd.JSONSchema{
					{
						Name:     "req",
						Type:     smd.Object,
						TypeName: "DeleteTaskRequest",
						Properties: smd.PropertyList{
							{
								Name: "taskId",
								Type: smd.Integer,
							},
						},
					},
				},
			},
			"UpdateStatus": {
				Parameters: []smd.JSONSchema{
					{
						Name:     "req",
						Type:     smd.Object,
						TypeName: "UpdateStatusRequest",
						Properties: smd.PropertyList{
							{
								Name: "taskId",
								Type: smd.Integer,
							},
							{
								Name: "statusId",
								Type: smd.Integer,
							},
						},
					},
				},
			},
			"GetStatuses": {
				Parameters: []smd.JSONSchema{},
				Returns: smd.JSONSchema{
					Type:     smd.Object,
					TypeName: "GetStatusesResponse",
					Properties: smd.PropertyList{
						{
							Name: "statuses",
							Type: smd.Array,
							Items: map[string]string{
								"$ref": "#/definitions/StatusResponse",
							},
						},
					},
					Definitions: map[string]smd.Definition{
						"StatusResponse": {
							Type: "object",
							Properties: smd.PropertyList{
								{
									Name: "statusId",
									Type: smd.Integer,
								},
								{
									Name: "Name",
									Type: smd.String,
								},
								{
									Name: "alias",
									Type: smd.String,
								},
							},
						},
					},
				},
			},
		},
	}
}

// Invoke is as generated code from zenrpc cmd
func (s TaskService) Invoke(ctx context.Context, method string, params json.RawMessage) zenrpc.Response {
	resp := zenrpc.Response{}
	var err error

	switch method {
	case RPC.TaskService.CreateTask:
		var args = struct {
			Req CreateTaskRequest `json:"req"`
		}{}

		if zenrpc.IsArray(params) {
			if params, err = zenrpc.ConvertToObject([]string{"req"}, params); err != nil {
				return zenrpc.NewResponseError(nil, zenrpc.InvalidParams, "", err.Error())
			}
		}

		if len(params) > 0 {
			if err := json.Unmarshal(params, &args); err != nil {
				return zenrpc.NewResponseError(nil, zenrpc.InvalidParams, "", err.Error())
			}
		}

		resp.Set(s.CreateTask(ctx, args.Req))

	case RPC.TaskService.GetTaskByPeriod:
		var args = struct {
			Req GetTaskByPeriodRequest `json:"req"`
		}{}

		if zenrpc.IsArray(params) {
			if params, err = zenrpc.ConvertToObject([]string{"req"}, params); err != nil {
				return zenrpc.NewResponseError(nil, zenrpc.InvalidParams, "", err.Error())
			}
		}

		if len(params) > 0 {
			if err := json.Unmarshal(params, &args); err != nil {
				return zenrpc.NewResponseError(nil, zenrpc.InvalidParams, "", err.Error())
			}
		}

		resp.Set(s.GetTaskByPeriod(ctx, args.Req))

	case RPC.TaskService.UpdateTitle:
		var args = struct {
			Req UpdateTitleRequest `json:"req"`
		}{}

		if zenrpc.IsArray(params) {
			if params, err = zenrpc.ConvertToObject([]string{"req"}, params); err != nil {
				return zenrpc.NewResponseError(nil, zenrpc.InvalidParams, "", err.Error())
			}
		}

		if len(params) > 0 {
			if err := json.Unmarshal(params, &args); err != nil {
				return zenrpc.NewResponseError(nil, zenrpc.InvalidParams, "", err.Error())
			}
		}

		resp.Set(s.UpdateTitle(ctx, args.Req))

	case RPC.TaskService.UpdateDescription:
		var args = struct {
			Req UpdateDescriptionRequest `json:"req"`
		}{}

		if zenrpc.IsArray(params) {
			if params, err = zenrpc.ConvertToObject([]string{"req"}, params); err != nil {
				return zenrpc.NewResponseError(nil, zenrpc.InvalidParams, "", err.Error())
			}
		}

		if len(params) > 0 {
			if err := json.Unmarshal(params, &args); err != nil {
				return zenrpc.NewResponseError(nil, zenrpc.InvalidParams, "", err.Error())
			}
		}

		resp.Set(s.UpdateDescription(ctx, args.Req))

	case RPC.TaskService.UpdateDeadLine:
		var args = struct {
			Req UpdateDeadLineRequest `json:"req"`
		}{}

		if zenrpc.IsArray(params) {
			if params, err = zenrpc.ConvertToObject([]string{"req"}, params); err != nil {
				return zenrpc.NewResponseError(nil, zenrpc.InvalidParams, "", err.Error())
			}
		}

		if len(params) > 0 {
			if err := json.Unmarshal(params, &args); err != nil {
				return zenrpc.NewResponseError(nil, zenrpc.InvalidParams, "", err.Error())
			}
		}

		resp.Set(s.UpdateDeadLine(ctx, args.Req))

	case RPC.TaskService.DeleteTask:
		var args = struct {
			Req DeleteTaskRequest `json:"req"`
		}{}

		if zenrpc.IsArray(params) {
			if params, err = zenrpc.ConvertToObject([]string{"req"}, params); err != nil {
				return zenrpc.NewResponseError(nil, zenrpc.InvalidParams, "", err.Error())
			}
		}

		if len(params) > 0 {
			if err := json.Unmarshal(params, &args); err != nil {
				return zenrpc.NewResponseError(nil, zenrpc.InvalidParams, "", err.Error())
			}
		}

		resp.Set(s.DeleteTask(ctx, args.Req))

	case RPC.TaskService.UpdateStatus:
		var args = struct {
			Req UpdateStatusRequest `json:"req"`
		}{}

		if zenrpc.IsArray(params) {
			if params, err = zenrpc.ConvertToObject([]string{"req"}, params); err != nil {
				return zenrpc.NewResponseError(nil, zenrpc.InvalidParams, "", err.Error())
			}
		}

		if len(params) > 0 {
			if err := json.Unmarshal(params, &args); err != nil {
				return zenrpc.NewResponseError(nil, zenrpc.InvalidParams, "", err.Error())
			}
		}

		resp.Set(s.UpdateStatus(ctx, args.Req))

	case RPC.TaskService.GetStatuses:
		resp.Set(s.GetStatuses(ctx))

	default:
		resp = zenrpc.NewResponseError(nil, zenrpc.MethodNotFound, "", nil)
	}

	return resp
}
